version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports: 
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-network

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    env_file: .env
    ports: 
      - "3306:3306"
    restart: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    ports: 
      - "9000:9000"
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network

volumes:
  mariadb_data:
    name: mariadb_data
    driver_opts:
      o: bind
      type: none
      device: /home/tmazitov/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver_opts:
      o: bind
      type: none
      device: /home/tmazitov/data/wordpress

networks:
  inception-network:
    name: inception-network
    driver: bridge